export const CLICKED_BUTTON_REQUEST = "CLICKED_BUTTON_REQUEST";
export const CLICKED_BUTTON_SUCCESS = "CLICKED_BUTTON_SUCCESS";
export const CLICKED_BUTTON_FAILURE = "CLICKED_BUTTON_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
